from music.music_module import FirstQuadrant, SecondQuadrant, ThirdQuadrant, FourthQuadrant

# 25 each add songs

# First Quadrant (Positive Valence, Positive Arousal)
# Valence (X): 1 to 10
# Arousal (Y): 1 to 10

song1 = FirstQuadrant("Good Time", "Owl City ft. Carly Rae Jepsen", (10, 10))
song2 = FirstQuadrant("Electric Feel", "MGMT", (9, 8))
song3 = FirstQuadrant("Pompeii", "Bastille", (8, 7))
song4 = FirstQuadrant("Take A Walk", "Passion Pit", (6, 8))
song5 = FirstQuadrant("We Are Young", "fun. ft. Janelle Monáe", (5, 7))
song6 = FirstQuadrant("Feel Good Inc.", "Gorillaz", (3, 5))
song7 = FirstQuadrant("Sweet Disposition", "The Temper Trap", (5, 5))
song8 = FirstQuadrant("Safe and Sound", "Capital Cities", (3, 4))
song9 = FirstQuadrant("A-Punk", "Vampire Weekend", (2, 3))
song10 = FirstQuadrant("Lisztomania", "Phoenix", (1, 1))
song11 = FirstQuadrant("Don't You Worry Child", "Swedish House Mafia ft. John Martin", (10, 6))
song12 = FirstQuadrant("Wake Me Up", "Avicii", (9, 5))
song13 = FirstQuadrant("Live It Up", "Aerosmith", (8, 4))
song14 = FirstQuadrant("On Top of the World", "Imagine Dragons", (6, 2))
song15 = FirstQuadrant("Dog Days Are Over", "Florence + The Machine", (6, 4))
song16 = FirstQuadrant("Shut Up and Dance", "Walk The Moon", (5, 1))
song17 = FirstQuadrant("Happy", "Pharrell Williams", (4, 10))
song18 = FirstQuadrant("Walking On Sunshine", "Katrina and the Waves", (3, 9))
song19 = FirstQuadrant("All Star", "Smash Mouth", (3, 7))
song20 = FirstQuadrant("Can't Stop the Feeling", "Justin Timberlake", (1, 7))
song21 = FirstQuadrant("Best Day of My Life", "American Authors", (7, 4))
song22 = FirstQuadrant("Go!", "The Chemical Brothers", (7, 3))
song23 = FirstQuadrant("It's My Life", "Bon Jovi", (7, 4))
song24 = FirstQuadrant("Everything Now", "Arcade Fire", (5, 3))
song25 = FirstQuadrant("Dance Monkey", "Tones and I", (6, 10))

# Second Quadrant (Negative Valence, Positive Arousal)
# Valence (X): -10 to -1
# Arousal (Y): 1 to 10

song26 = SecondQuadrant("Runaway", "Kanye West", (-10, 10))
song27 = SecondQuadrant("The Pretender", "Foo Fighters", (-9, 7))
song28 = SecondQuadrant("Hurt", "Nine Inch Nails", (-8, 9))
song29 = SecondQuadrant("Fell In Love With A Girl", "The White Stripes", (-9, 4))
song30 = SecondQuadrant("No One Knows", "Queens of the Stone Age", (-6, 8))
song31 = SecondQuadrant("Mr. Brightside", "The Killers", (-5, 4))
song32 = SecondQuadrant("Bury a Friend", "Billie Eilish", (-4, 4))
song33 = SecondQuadrant("Knights of Cydonia", "Muse", (-3, 3))
song34 = SecondQuadrant("The Hand That Feeds", "Nine Inch Nails", (-2, 4))
song35 = SecondQuadrant("Reptilia", "The Strokes", (-1, 1))
song36 = SecondQuadrant("Heart-Shaped Box", "Nirvana", (-10, 4))
song37 = SecondQuadrant("Toxic", "Britney Spears", (-9, 3))
song38 = SecondQuadrant("Paranoid", "Black Sabbath", (-8, 2))
song39 = SecondQuadrant("Unfinished Sympathy", "Massive Attack", (-7, 1))
song40 = SecondQuadrant("Back to Black", "Amy Winehouse", (-6, 10))
song41 = SecondQuadrant("Last Resort", "Papa Roach", (-5, 9))
song42 = SecondQuadrant("Stressed Out", "Twenty One Pilots", (-4, 8))
song43 = SecondQuadrant("Take the Power Back", "Rage Against the Machine", (-3, 7))
song44 = SecondQuadrant("Knights of Cydonia", "Muse", (-2, 6))
song45 = SecondQuadrant("The Kill", "30 Seconds to Mars", (-1, 5))
song46 = SecondQuadrant("Stronger", "Kanye West", (-8, 4))
song47 = SecondQuadrant("Smells Like Teen Spirit", "Nirvana", (-7, 3))
song48 = SecondQuadrant("Helena", "My Chemical Romance", (-6, 2))
song49 = SecondQuadrant("Sugar, We're Goin Down", "Fall Out Boy", (-5, 1))
song50 = SecondQuadrant("Sugar", "System of a Down", (-4, 10))

# Third Quadrant (Negative Valence, Negative Arousal)
# Valence (X): -10 to -1
# Arousal (Y): -10 to -1

song51 = ThirdQuadrant("The Night We Met", "Lord Huron", (-10, -10))
song52 = ThirdQuadrant("Self Control", "Frank Ocean", (-9, -9))
song53 = ThirdQuadrant("The Sound of Silence", "Simon & Garfunkel", (-8, -6))
song54 = ThirdQuadrant("No One Noticed", "The Marías", (-7, -9))
song55 = ThirdQuadrant("Creep", "Radiohead", (-6, -7))
song56 = ThirdQuadrant("Sailor Song", "Gigi Perez", (-6, -5))
song57 = ThirdQuadrant("Breathe Me", "Sia", (-2, -4))
song58 = ThirdQuadrant("All I Want", "Kodaline", (-3, -3))
song59 = ThirdQuadrant("Tears Dry on Their Own", "Amy Winehouse", (-1, -2))
song60 = ThirdQuadrant("Somewhere Over The Rainbow", "Israel Kamakawiwo'ole", (-1, -1))
song61 = ThirdQuadrant("Mad World", "Gary Jules", (-9, -5))
song62 = ThirdQuadrant("Ain't No Sunshine", "Bill Withers", (-9, -4))
song63 = ThirdQuadrant("Under the Bridge", "Red Hot Chili Peppers", (-7, -3))
song64 = ThirdQuadrant("About You", "The 1975", (-7, -2))
song65 = ThirdQuadrant("Say Something", "A Great Big World", (-6, -1))
song66 = ThirdQuadrant("Yesterday", "The Beatles", (-5, -10))
song67 = ThirdQuadrant("When We Were Young", "Adele", (-4, -9))
song68 = ThirdQuadrant("Let Her Go", "Passenger", (-3, -8))
song69 = ThirdQuadrant("Someone Like You", "Adele", (-2, -7))
song70 = ThirdQuadrant("The River", "Bruce Springsteen", (-1, -6))
song71 = ThirdQuadrant("Skinny Love", "Bon Iver", (-8, -6))
song72 = ThirdQuadrant("Sparks", "Coldplay", (-7, -4))
song73 = ThirdQuadrant("My Love Mine All Mine", "Mitski", (-6, -2))
song74 = ThirdQuadrant("The Scientist", "Coldplay", (-5, -1))
song75 = ThirdQuadrant("The Night We Met", "Lord Huron", (-4, -5))

# Fourth Quadrant (Positive Valence, Negative Arousal)
# Valence (X): 1 to 10
# Arousal (Y): -10 to -1

song76 = FourthQuadrant("The Lazy Song", "Bruno Mars", (10, -10))
song77 = FourthQuadrant("Banana Pancakes", "Jack Johnson", (9, -9))
song78 = FourthQuadrant("Breathe", "Pink Floyd", (8, -5))
song79 = FourthQuadrant("Wonderful Tonight", "Eric Clapton", (7, -9))
song80 = FourthQuadrant("Landslide", "Fleetwood Mac", (6, -6))
song81 = FourthQuadrant("Harvest Moon", "Neil Young", (5, -2))
song82 = FourthQuadrant("The Weight", "The Band", (3, -4))
song83 = FourthQuadrant("Stay", "Rihanna ft. Mikky Ekko", (3, -3))
song84 = FourthQuadrant("Gravity", "John Mayer", (2, -2))
song85 = FourthQuadrant("I Will Follow You Into the Dark", "Death Cab for Cutie", (1, -1))
song86 = FourthQuadrant("Let It Be", "The Beatles", (10, -4))
song87 = FourthQuadrant("Come Away With Me", "Norah Jones", (9, -3))
song88 = FourthQuadrant("Jolene", "Dolly Parton", (8, -2))
song89 = FourthQuadrant("Fields of Gold", "Sting", (7, -1))
song90 = FourthQuadrant("Wonderwall", "Oasis", (6, -5))
song91 = FourthQuadrant("Your Best American Girl", "Mitski", (5, -7))
song92 = FourthQuadrant("Hallelujah", "Jeff Buckley", (4, -7))
song93 = FourthQuadrant("The One That Got Away", "Katy Perry", (3, -8))
song94 = FourthQuadrant("Fix You", "Coldplay", (2, -9))
song95 = FourthQuadrant("Hurt", "Christina Aguilera", (1, -10))
song96 = FourthQuadrant("I Won't Give Up", "Jason Mraz", (3, -8))
song97 = FourthQuadrant("Summertime", "DJ Jazzy Jeff & The Fresh Prince", (2, -1))
song98 = FourthQuadrant("Yellow", "Coldplay", (1, -3))
song99 = FourthQuadrant("At Last", "Etta James", (6, -2))
song100 = FourthQuadrant("Moon River", "Andy Williams", (7, -3))